services:
  api:
    # Constrói a imagem Docker a partir do Dockerfile no diretório atual.
    build: .

    # Define um nome para o contêiner para facilitar a referência.
    container_name: imersao_api

    # Mapeia a porta 8080 da sua máquina (host) para a porta 8080 do contêiner.
    ports:
      - "8080:8080"

    # Monta o diretório do projeto local dentro do contêiner.
    # Isso é essencial para o desenvolvimento, pois permite que o "hot-reload"
    # do uvicorn detecte alterações no código e reinicie o servidor automaticamente.
    volumes:
      - .:/app
