name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to Cloud Run'
        required: true
        default: true
        type: boolean

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # Permissões necessárias para autenticação com Workload Identity Federation
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check if secrets are being called
        env:
          PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GCP_REGION }}
          REPOSITORY_NAME: ${{ secrets.GCP_REPOSITORY_NAME }}
          IMAGE_NAME: ${{ secrets.GCP_SERVICE_NAME }}
        run: |
          echo "$PROJECT_NUMBER"
          echo "$PROJECT_ID"
          echo "$REGION"
          echo "$REPOSITORY_NAME"
          echo "$IMAGE_NAME"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Execute Deploy Script
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GCP_REGION }}
          REPOSITORY_NAME: ${{ secrets.GCP_REPOSITORY_NAME }}
          IMAGE_NAME: ${{ secrets.GCP_SERVICE_NAME }}
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
